
volumes:
  svj-data:

services:


  db:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: svj
      POSTGRES_PASSWORD: password
      POSTGRES_DB: svj
    volumes:
      - svj-data:/var/lib/postgresql/data

